blog/models/__init__.py
from blog.configurations.database import db

blog/models/user_model.py
from re import A
from . import db


class UserModel(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    username = db.Column(db.String, nullable=False, unique=True)
    email = db.Column(db.String, nullable=False, unique=True)
    password = db.Column(db.String, nullable=False)

blog/forms/auth_form.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField, BooleanField, StringField
from flask_wtf.html5 import EmailInput


class LoginForm(FlaskForm):
    email = StringField("email")
    password = PasswordField("password")
    remeberme = BooleanField("remember-me")

    submit = SubmitField("login")

blog/app.py
from flask import Flask
from os import getenv

from blog.configurations import database
from blog.configurations import migration
from blog.configurations import authentication
from blog import views


def create_app():
    app = Flask(__name__)
    # Ola moçada
    app.config["SQLALCHEMY_DATABASE_URI"] = getenv("DATABASE_URL_UPDATED")
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.config["SECRET_KEY"] = getenv("SECRET_KEY")

    database.init_app(app)
    migration.init_app(app)
    authentication.init_app(app)
    views.init_app(app)

    return app

blog/views/__init__.py
from flask import Flask


def init_app(app: Flask):
    from .auth_view import bp as bp_auth

    app.register_blueprint(bp_auth, url_prefix="/auth")

    from .home_view import bp as bp_home

    app.register_blueprint(bp_home, url_prefix="/home")

blog/views/auth_view.py
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from flask_login import login_user
from werkzeug.exceptions import NotFound

from blog.forms.auth_form import LoginForm
from blog.models.user_model import UserModel

bp = Blueprint("auth", __name__)


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        email = request.form.get("email")
        password = request.form.get("password")
        rememberme = request.form.get("rememberme")
        found_user: UserModel = UserModel.query.filter_by(email=email)
        if not found_user or password != found_user.password:
            raise NotFound("Email or password are not correct")
        login_user(found_user, rememberme)

        next_access: str = request.args.get("next")
        if not next_access or next_access.startswith("/"):
            next_access = "home.home_render"
        return redirect(url_for(next_access))
    return render_template("login.html", form=form)


@bp.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "GET":
        return render_template("signup.html")

    session = current_app.db.session

    name = request.form.get("name")
    username = request.form.get("username")
    email = request.form.get("email")
    password = request.form.get("password")

    new_user = UserModel(name=name, username=username, email=email, password=password)
    session.add(new_user)
    session.commit()

    return redirect(url_for("home.home_render"))

blog/views/home_view.py
from flask import Blueprint, render_template
from flask_login import login_required

bp = Blueprint("home", __name__)


@bp.route("/", methods=["GET"])
@login_required
def home_render():
    return render_template("home.html")


# belezinha

blog/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    Ola
</body>

</html>

blog/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="{{url_for('auth.login')}}" method="POST">
        <label for="email">{{form.email.label}}</label>
        {{form.email()}}

        <label for="password">{{form.password.label}}</label>
        {{form.password()}}

        <label for="rememberme">{{form.remeberme.label}}</label>
        {{form.remeberme()}}

        {{form.submit}}
    </form>
</body>

</html>

blog/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="{{url_for('auth.signup')}}" method="POST">
        <label for="name">Name:</label>
        <input name="name" type="text">


        <label for="username">Username:</label>
        <input name="username" type="text">

        <label for="email">Email:</label>
        <input name="email" type="text">

        <label for="password">Password:</label>
        <input name="password" type="password">

        <button type="submit">Signup</button>
    </form>
</body>

</html>